# Generated by Django 6.0.4 on 2026-06-08 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('emi_reminder', 'EMI Reminder'), ('savings_reminder', 'Savings Reminder'), ('monthly_report', 'Monthly Report'), ('investment_update', 'Investment Update'), ('goal_achieved', 'Goal Achieved'), ('general', 'General')], default='general', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_alert_inapp', models.BooleanField(default=True)),
                ('emi_reminder_inapp', models.BooleanField(default=True)),
                ('savings_reminder_inapp', models.BooleanField(default=True)),
                ('monthly_report_inapp', models.BooleanField(default=True)),
                ('investment_update_inapp', models.BooleanField(default=True)),
                ('goal_achieved_inapp', models.BooleanField(default=True)),
                ('budget_alert_email', models.BooleanField(default=True)),
                ('emi_reminder_email', models.BooleanField(default=True)),
                ('savings_reminder_email', models.BooleanField(default=False)),
                ('monthly_report_email', models.BooleanField(default=True)),
                ('investment_update_email', models.BooleanField(default=False)),
                ('goal_achieved_email', models.BooleanField(default=True)),
                ('emi_reminder_days_before', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
